FROM php:8.2-apache

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        default-mysql-client \
        git \
        libfreetype6-dev \
        libicu-dev \
        libjpeg62-turbo-dev \
        libonig-dev \
        libpng-dev \
        libxml2-dev \
        libxslt-dev \
        libzip-dev \
        locales \
        nodejs \
        npm \
        unzip \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && echo "fr_FR.UTF-8 UTF-8" >> /etc/locale.gen \
    && locale-gen \
    && curl -sS https://getcomposer.org/installer | php -- \
    && mv composer.phar /usr/local/bin/composer \
    && docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
        calendar \
        dom \
        gd \
        intl \
        mbstring \
        mysqli \
        opcache \
        pdo \
        pdo_mysql \
        soap \
        xsl \
        zip \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && a2enmod rewrite \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /var/www

COPY docker/php/php/php.ini /usr/local/etc/php/php.ini
COPY docker/php/vhosts/prod.conf /etc/apache2/sites-available/000-default.conf
COPY . .
COPY wp-config-prod.php /var/www/wp-config.php

RUN cd wp-content/plugins/change-me-theme \
    && composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader \
    && cd /var/www/wp-content/plugins/dressme \
    && composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

RUN cd wp-content/themes/change-me/assets \
    && npm install \
    && npm run build \
    && rm -rf node_modules

RUN mkdir -p /var/www/wp-content/uploads /var/www/wp-content/upgrade \
    && chown -R www-data:www-data \
        /var/www/wp-content/uploads \
        /var/www/wp-content/upgrade \
        /var/www/wp-content/plugins/change-me-theme/config
