services:
  db:
    image: mariadb:10.11
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - wordpress-db-data:/var/lib/mysql

  www:
    build:
      context: .
      dockerfile: docker/php/Dockerfile.prod
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_HOST: db
      BASIC_AUTH_USER: ${BASIC_AUTH_USER}
      BASIC_AUTH_PASSWORD: ${BASIC_AUTH_PASSWORD}
      WORDPRESS_HOME: "https://boutique-test.joeydecroix.com"
      WORDPRESS_SITEURL: "https://boutique-test.joeydecroix.com"
      WP_ENVIRONMENT_TYPE: production
    volumes:
      - wordpress-uploads:/var/www/wp-content/uploads
      - wordpress-plugins:/var/www/wp-content/plugins
      - wordpress-languages:/var/www/wp-content/languages

volumes:
  wordpress-db-data:
  wordpress-uploads:
  wordpress-plugins:
  wordpress-languages:
